spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdb
    username: root
    password: welcome1
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
    continue-on-error: true
    hikari:
      maximumPoolSize: 2